name: base85
description: Base85 encoder/decoder written in native Dart.
version: 1.0.4
homepage: https://github.com/litaoh/base85

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
